name: Executar script 2x por dia

#quando quiser manual
on:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 18 * * *'
  workflow_dispatch:

#quando quiser automatico via cron
#on:
#  schedule:
#    - cron: '0 6 * * *'   # Executa às 06:00 UTC
#    - cron: '0 18 * * *'  # Executa às 18:00 UTC
#
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do repositório
      uses: actions/checkout@v4

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Rodar script Python
      run: python preco_aliexpress.py
